#+TITLE: How to Visualize a SQLite Database using SchemaCralwer
#+DESCRIPTION: This article provides a comprehensive guide on how to visualize a SQLite database using SchemaCrawler with Docker. SchemaCrawler is a powerful database schema discovery and comprehension tool that can be used to generate ER diagrams, database documentation, and other reports for a variety of databases, including SQLite. 
#+KEYWORDS: SQLite, SchemaCrawler, Docker, ER diagram, database visulization, Django, db.sqlite3

Visualizing a SQLite database can be helpful for understanding the design
of the database, for identifying potential problems, and for communicating
the database design to others. There are a number of ways to visualize a
SQLite database, but one of the most convenient ways is to use SchemaCrawler
with Docker.

[[https://www.schemacrawler.com/index.html][SchemaCrawler]] is a free and open-source database schema discovery and
comprehension tool. It can be used to generate ER diagrams, database
documentation, and other reports for a variety of databases, including SQLite.

To visualize a SQLite database using SchemaCrawler with Docker,
you can run this:

#+BEGIN_SRC bash
  docker run \      
  --mount type=bind,source="$(pwd)",target=/home/schcrwlr \
  --rm -it \
  schemacrawler/schemacrawler \
  /opt/schemacrawler/bin/schemacrawler.sh \
  --info-level=standard \	
  --server=sqlite \
  --database=db.sqlite3 \
  --command=schema \
  --output-format=png \
  --output-file=graph.png \
#+END_SRC

This will generate an ER graph in PNG format, which will be saved to the
current directory.

You can also use the SchemaCrawler command-line interface to generate ER
graphs in other formats, such as SVG and PDF. To do this,
simply change the -outputformat argument to the desired format.

Here are some additional options that you can use with the SchemaCrawler command-line interface:

#+BEGIN_SRC
--infolevel=maximum: This will generate the most detailed ER graph.
--showRelationships=true: This will show the relationships between the tables in the ER graph.
--hideColumnDetails=true: This will hide the column details in the ER graph.
#+END_SRC

Once you have generated an ER graph, you can use it to visualize the
structure of your database and to identify any potential problems.


** Conclusion

Using SchemaCrawler with Docker is a convenient and reliable way to visualize
SQLite databases. SchemaCrawler is a powerful tool that can be used to
generate ER diagrams, database documentation, and other reports for a
variety of databases. Docker is a containerization platform that allows you
to package and deploy applications in isolated containers.

By combining SchemaCrawler with Docker, you can easily visualize your
SQLite databases on any system, regardless of the operating system or
the software that is installed on the system.

